### Health Check - GET simples
GET http://localhost:5000/health

###
### Criar novo pedido
POST http://localhost:5000/orders
Content-Type: application/json

###
### Buscar pedido por ID
### Substitua {order_id} pelo ID retornado na criação
GET http://localhost:5000/orders/6930267f3a7f975afe5688f9

###
### Mudar status do pedido
### Substitua {order_id} pelo ID retornado na criação
PATCH http://localhost:5000/orders/6930267f3a7f975afe5688f9/status
Content-Type: application/json

